# Declare your Buildkite pipelines below
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-consumption_framework
  description: Buildkite Pipeline for consumption_framework
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/consumption_framework

spec:
  type: buildkite-pipeline
  owner: group:customer-architects
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: consumption_framework
      description: 
    spec:
      repository: elastic/consumption_framework
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        customer-architects:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
