FROM public.ecr.aws/lambda/python:3.11

# Copy requirements.txt
COPY requirements_lambda.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements_lambda.txt

# Copy function code
ADD consumption consumption
COPY lambda_function.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler
CMD [ "lambda_function.handler" ]